services:
  minecraft:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minecraft-server
    working_dir: /data
    volumes:
      - ./server:/data
    ports:
      - "${HOST_MC_PORT:-25565}:25565"
      - "${HOST_RCON_PORT:-25575}:25575"
      - "${HOST_TTYD_PORT:-7681}:7681"
    restart: unless-stopped
    stdin_open: true
    tty: true
